### ISSUE TITLE
AFC-1323 Create rest client/server Suborder module

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-sale#1]
Specification moved to https://github.com/vertelab/odoo-af/issues/303

**Comment by arturchilangwa-vertel** [comment]
@AnatoliiYakymets 
Opened this PR https://github.com/vertelab/odoo-sale/pull/9 to replace https://github.com/vertelab/odoo-sale/pull/8. The old one was pointing to the wrong base branch.
